CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password_hash BLOB NOT NULL,
	activated BOOLEAN NOT NULL DEFAULT false,
	role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
	version INTEGER NOT NULL DEFAULT 1
);

CREATE TRIGGER set_updated_at
AFTER UPDATE ON users
FOR EACH ROW
BEGIN
	UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;

